<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Authors>Marius Göcke</Authors>
        <Version>0.0.1</Version>
        <AssemblyVersion>0.0.1</AssemblyVersion>
        <FileVersion>0.0.1</FileVersion>
        <SelfContained>false</SelfContained>
        <IsPackable>false</IsPackable>
        <PreserveCompilationContext>false</PreserveCompilationContext>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <Copyright>Copyright © 2023 Marius Göcke</Copyright>
        <Description>OpenDMSBackendTests is the test-project for OpenDMSBackend.</Description>
        <PackageProjectUrl>https://projects.aniondev.de/PublicProjects/Common/OpenDMSBackend</PackageProjectUrl>
        <RepositoryUrl>https://projects.aniondev.de/PublicProjects/Common/OpenDMSBackend.git</RepositoryUrl>
        <RootNamespace>OpenDMSBackend.Tests</RootNamespace>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
        <Nullable>enable</Nullable>
        <Configurations>Development;QualityCheck;Productive</Configurations>
        <IsTestProject>true</IsTestProject>
        <LangVersion>11.0</LangVersion>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <OutputPath>..\Other\Artifacts\BuildResultTests_DotNet_win-x64</OutputPath>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <WarningLevel>4</WarningLevel>
        <Prefer32Bit>false</Prefer32Bit>
        <SignAssembly>True</SignAssembly>
        <AssemblyOriginatorKeyFile>..\..\Other\Resources\PublicKeys\StronglyNamedKey\OpenDMSPublicKey.snk</AssemblyOriginatorKeyFile>
        <DelaySign>True</DelaySign>
        <NoWarn>1701;1702;CA1822;CS1591;CS1573;IDE0045;IDE0046;IDE0054;IDE0058;IDE0074;IDE0090;IDE0017;IDE0063;CA1859</NoWarn>
        <WarningsAsErrors>NU1605</WarningsAsErrors>
        <ErrorLog>..\Other\Resources\CodeAnalysisResult\OpenDMSBackendTests.sarif</ErrorLog>
        <OutputType>Library</OutputType>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)'=='Development'">
        <DebugType>full</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <Optimize>false</Optimize>
        <DefineConstants>TRACE;DEBUG;Development</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)'=='QualityCheck'">
        <DebugType>portable</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <Optimize>false</Optimize>
        <DefineConstants>TRACE;QualityCheck</DefineConstants>
        <ErrorReport>none</ErrorReport>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)'=='Productive'">
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
        <Optimize>true</Optimize>
        <DefineConstants>Productive</DefineConstants>
        <ErrorReport>none</ErrorReport>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\GRYLibrary\GRYLibrary\GRYLibrary\GRYLibrary.csproj" />
        <ProjectReference Include="..\OpenDMSBackend\OpenDMSBackend.csproj" />
        <PackageReference Include="CommandLineParser" Version="2.9.1" />
        <PackageReference Include="coverlet.collector" Version="6.0.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.msbuild" Version="6.0.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="ExtendedXmlSerializer" Version="3.8.0" />
        <PackageReference Include="HtmlAgilityPack" Version="1.11.71" />
        <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
        <PackageReference Include="Microsoft.CodeCoverage" Version="17.11.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="8.0.10" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
        <PackageReference Include="Microsoft.Extensions.Logging.EventLog" Version="8.0.1" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
        <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
        <PackageReference Include="Moq" Version="4.20.72" />
        <PackageReference Include="MSTest.TestAdapter" Version="3.6.2" />
        <PackageReference Include="MSTest.TestFramework" Version="3.6.2" />
        <PackageReference Include="Nethereum.Web3" Version="4.26.0" />
        <PackageReference Include="NJsonSchema" Version="11.0.2" />
        <PackageReference Include="NSwag.AspNetCore" Version="14.1.0" />
        <PackageReference Include="prometheus-net" Version="8.2.1" />
        <PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
        <PackageReference Include="System.Reactive" Version="6.0.1" />
    </ItemGroup>
</Project>