worker_processes             1;
pid                          /var/run/nginx.pid;

events {
    worker_connections       1024;
}

http {
    include                  /etc/nginx/mime.types;
    default_type             application/octet-stream;
    log_format               main  '$remote_addr - $remote_user [$time_local] "$request" ' '$status $body_bytes_sent "$http_referer" ' '"$http_user_agent" "$http_x_forwarded_for"';
    access_log               /dev/stdout;
    error_log                /dev/stderr;
    keepalive_timeout        65;
    client_max_body_size     800M;
    server_tokens            off;
    add_header               X-Content-Type-Options nosniff;
    add_header               X-Frame-Options DENY;
    add_header               X-XSS-Protection "1; mode=block";
    add_header               Referrer-Policy "origin";

    server {
        listen               443 ssl;
        server_name          opendms.test.local;
        ssl_protocols        TLSv1.2 TLSv1.3;
        ssl_certificate      /Workspace/Certificates/OpenDMSDevelopmentCertificate.crt;
        ssl_certificate_key  /Workspace/Certificates/OpenDMSDevelopmentCertificate.key;
        proxy_set_header     X-Real-IP  $remote_addr;
        proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header     Host $http_host;
        proxy_redirect       off;
        location /API/ {
            proxy_pass       http://host.docker.internal:80;
        }
        location / {
            index            /index.html;
            proxy_pass       http://host.docker.internal:4200;
        }
    }
}
