@startuml RuntimeViewQuickTest
title Runtime-view quick test

actor "User" as user
note as UserNote
  The user calls https://opendms.test.local:443
end note
user .. UserNote

[OpenDMS (:443)] as OpenDMS
note as OpenDMSNote
    Started by container-engine (for example docker).
    The domain can be set using the commandline-parameter "--InitialDomain <domain>".
    Backend and frontend are running in the container.
    Transient will be used as persistence.
end note 
OpenDMS .. OpenDMSNote

user --> OpenDMS
@enduml
