services:

  opendms_database:
    container_name: "opendms_database"
    image: ${image_postgresql}
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pa55w0rd
      POSTGRES_DB: OpenDMSDatabase
      PGDATA: /var/lib/postgresql/data
    expose:
      - "5432"
    volumes:
      - ./Volumes/OpenDMSPostgreSQLData:/var/lib/postgresql/data
    networks:
      - opendms_net
    command: >
      postgres -c log_connections=on -c log_disconnections=on

  opendms_database_administration:
    image: ${image_adminer}
    container_name: "opendms_database_administration"
    expose:
      - "8080"
    depends_on:
      - opendms_database
    networks:
      - opendms_net

networks:
  opendms_net:
    external: true
