version: "3.2"

services:
  opendmsbackend_database:
    container_name: "opendmsbackend_database"
    image: postgres:17.6
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pa55w0rd
      POSTGRES_DB: OpenDMSDatabase
#      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
#    volumes:
#      - OpenDMSPostgreSQLData:/var/lib/postgresql/data
    networks:
      - opendms_net
    command: >
      postgres -c log_connections=on -c log_disconnections=on

  opendmsbackend_database_administration:
    image: adminer:4.8.1
    container_name: "opendmsbackend_database_administration"
    ports:
      - 8080:8080
    depends_on:
      - opendmsbackend_database
    networks:
      - opendms_net

networks:
  opendms_net:
    external: true
