<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Authors>Marius Göcke</Authors>
        <Version>1.1.1</Version>
        <AssemblyVersion>1.1.1</AssemblyVersion>
        <FileVersion>1.1.1</FileVersion>
        <SelfContained>false</SelfContained>
        <IsPackable>false</IsPackable>
        <PreserveCompilationContext>false</PreserveCompilationContext>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <Copyright>Copyright © 2025 Marius Göcke</Copyright>
        <Description>OpenDMSBackend is the backend of OpenDMS.</Description>
        <PackageProjectUrl>https://projects.aniondev.de/PublicProjects/Common/OpenDMSBackend</PackageProjectUrl>
        <RepositoryUrl>https://projects.aniondev.de/PublicProjects/Common/OpenDMSBackend.git</RepositoryUrl>
        <RootNamespace>OpenDMSBackend.Core</RootNamespace>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
        <Nullable>enable</Nullable>
        <Configurations>Development;QualityCheck;Productive</Configurations>
        <IsTestProject>false</IsTestProject>
        <LangVersion>11.0</LangVersion>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <OutputPath>..\Other\Artifacts\BuildResult_DotNet_win-x64</OutputPath>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <WarningLevel>4</WarningLevel>
        <Prefer32Bit>false</Prefer32Bit>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>..\..\Other\Resources\PublicKeys\StronglyNamedKey\OpenDMSPublicKey.snk</AssemblyOriginatorKeyFile>
        <DelaySign>true</DelaySign>
        <NoWarn>1701;1702;CA1822;CS1591;CS1573;IDE0045;IDE0046;IDE0054;IDE0058;IDE0074;IDE0090;CS8002;CA1859;IDE0042;IDE0017;IDE0034</NoWarn>
        <WarningsAsErrors>NU1605</WarningsAsErrors>
        <ErrorLog>..\Other\Resources\CodeAnalysisResult\OpenDMSBackend.sarif</ErrorLog>
        <OutputType>Exe</OutputType>
        <DocumentationFile>..\Other\Artifacts\MetaInformation\OpenDMSBackend.xml</DocumentationFile>
        <StartupObject>OpenDMSBackend.Core.Program</StartupObject>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)'=='Development'">
        <DebugType>full</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <Optimize>false</Optimize>
        <DefineConstants>TRACE;DEBUG;Development</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)'=='QualityCheck'">
        <DebugType>portable</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <Optimize>false</Optimize>
        <DefineConstants>TRACE;QualityCheck</DefineConstants>
        <ErrorReport>none</ErrorReport>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)'=='Productive'">
        <DebugType>portable</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <Optimize>true</Optimize>
        <DefineConstants>Productive</DefineConstants>
        <ErrorReport>none</ErrorReport>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="CommandLineParser" Version="2.9.1" />
        <PackageReference Include="ExtendedXmlSerializer" Version="3.9.6" />
        <PackageReference Include="Microsoft.ClearScript.Core" Version="7.5.0" />
        <PackageReference Include="Microsoft.ClearScript.V8" Version="7.5.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.9" />
        <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
        <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
        <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="9.0.9" />
        <PackageReference Include="Microsoft.Extensions.Logging.EventLog" Version="9.0.9" />
        <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
        <PackageReference Include="Npgsql" Version="9.0.3" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
        <PackageReference Include="prometheus-net" Version="8.2.1" />
        <PackageReference Include="SimpleOCRLibrary" Version="1.3.0" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
        <PackageReference Include="SkiaSharp" Version="3.119.1" />
        <PackageReference Include="System.Collections.Immutable" Version="9.0.9" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.9" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.9" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.9" />
        <PackageReference Include="NJsonSchema" Version="11.5.1" />
        <PackageReference Include="NSwag.AspNetCore" Version="14.6.1" />
        <PackageReference Include="System.Drawing.Common" Version="9.0.9" />
        <PackageReference Include="System.Reactive" Version="6.1.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
        <PackageReference Include="Tesseract" Version="5.2.0" />
        <PackageReference Include="GRYLIbrary" Version="0.12.167" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Resources\**">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </EmbeddedResource>
    </ItemGroup>
</Project>