version: "3.2"

services:
  opendmsbackend_database:
    container_name: "opendmsbackend_database"
    image: mariadb:11.5.2
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: pa55w0rd
      MARIADB_ROOT_PASSWORD: R00tpa55w0rd
      MARIADB_DATABASE: OpenDMSDatabase
    volumes:
      - ./Volumes/Data:/var/lib/mysql
    networks:
      - opendms_net

  opendmsbackend_database_administration:
    image: adminer:4.8.1
    container_name: "opendmsbackend_database_administration"
    networks:
      - opendms_net

networks:
  opendms_net:
    external: true
